version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      OPENWEATHER_API_URL: https://api.openweathermap.org/data/2.5/weather
